# The sms-over-xmpp config file is TOML.  To a first approximation,
# this is just the classic INI format.
#
# See https://github.com/toml-lang/toml for full details about the
# format.

# The xmpp section holds all configuration related to the XMPP
# protocol.  This includes information about the server to which this
# component connects and the way this component interprets/generates
# XMPP stanzas.
[xmpp]
# host is the domain name or IP address of the XMPP server to which
# this component connects.  The XMPP server can run locally or
# remotely.  TLS connections to the server are not supported so be
# cautious if you use a remote server.
host = "127.0.0.1"

# port is the port on which the XMPP server is listening.
port = 5347

# name is the domain name under which this component will operate.
# This must match the component's domain name in your XMPP server.
# Otherwise, the component handshake will fail.
name = "sms.example.com"

# secret is the secret shared with the XMPP server.  This must
# match the secret configured in the XMPP server.
secret = "secret shared with the XMPP server"
